baseURL: 'https://akhilpandey95.github.io/'
builddrafts: false
canonifyurls: true
contentdir: content
languageCode: en-US
layoutdir: layouts
publishdir: public
theme: PaperMod
author: Akhil Pandey
title: Akhil Pandey
pygmentsuseclasses: true
pluralizelisttitles: false
permalinks:
  blog: 'blog/:slug/'
menu:
  main:
    - name: About
      weight: 2
      identifier: about
      url: /about/
    - name: Projects
      weight: 4
      identifier: projects
      url: /projects/
    - name: Blog
      weight: 3
      identifier: blog
      url: /blog/
params:
  math: true
  social: true
  analytics:
    google:
      SiteVerificationTag: "UA-135077366-1"
  homeInfoParams:
    Title: నమస్తే, My name is Akhil | 🥐 ☕ 🍜
    Content: I am Research Scientist at the [Center for Science of Science and Innovation](https://www.kellogg.northwestern.edu/research/science-of-science.aspx) working for [Dashun Wang](https://www.dashunwang.com/) at the Kellogg School of Management, Northwestern University. [more...](/about)
  socialIcons:
    - name: "Github"
      url: "https://github.com/akhilpandey95"
    - name: "LinkedIn"
      url: "https://www.linkedin.com/in/akhilpandey/"
    - name: "Twitter"
      url: "https://twitter.com/akhilpandey95"
    - name: "Google Scholar"
      url: "https://scholar.google.com/citations?user=gG8VifwAAAAJ&hl=en"
    - name: "Instagram"
      url: "https://www.instagram.com/noiretblanc_stories/"
  include_rss: false
  latestpostscount: 5
  i18n_flags: false
  author: Akhil Pandey
  cachebuster: true
  dateform: 'Jan 2, 2006'
  dateformfull: 'Mon Jan 2 2006 15:04:05 MST'
  description: Don't panic
  email: akhilpandey95@icloud.com
  extracssfiles:
    - /css/override.css
  github: 'https://github.com/akhilpandey95'
  selfintro: ''
  highlightjs: true
  avatar: img/me.jpeg
  gatracker: XYZ
  initials: ad
  ShowToc: true
  ShowReadingTime: true


